[theme]
primaryColor="#4B8BBE"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

dependencyMode = "requirements"
maxCacheAge = 0  # Disable cache
installTimeout = 600  # 10-minute timeout